// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultF irebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeUK4tdT01zWdZAisDPPyKLaBxoovn9EQ',
    appId: '1:405622289601:web:fba5f6d2e9eaff8e6b1040',
    messagingSenderId: '405622289601',
    projectId: 'auty-42336',
    authDomain: 'auty-42336.firebaseapp.com',
    storageBucket: 'auty-42336.firebasestorage.app',
    measurementId: 'G-BYTLVRRFPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmReH_YIiJWFVeffoKLWmruFTS9DkCOCo',
    appId: '1:405622289601:android:59966d4a7e48ba5e6b1040',
    messagingSenderId: '405622289601',
    projectId: 'auty-42336',
    storageBucket: 'auty-42336.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeUK4tdT01zWdZAisDPPyKLaBxoovn9EQ',
    appId: '1:405622289601:web:5e5bcd44cf153b3e6b1040',
    messagingSenderId: '405622289601',
    projectId: 'auty-42336',
    authDomain: 'auty-42336.firebaseapp.com',
    storageBucket: 'auty-42336.firebasestorage.app',
    measurementId: 'G-Z267M9G921',
  );
}
